document.querySelectorAll('nav button').forEach((button,index)=>{if(!index)button.classList.add('on');button.addEventListener('click',()=>{document.querySelectorAll('.tab').forEach(tab=>tab.classList.remove('active'));document.querySelectorAll('nav button').forEach(item=>item.classList.remove('on'));document.getElementById(button.dataset.tab)?.classList.add('active');button.classList.add('on');window.scrollTo({top:0,behavior:'smooth'});})});
const pageHash=document.querySelector('meta[name="report-version"]')?.content||'';
const updateButton=document.getElementById('manual-refresh');
const repairButton=document.getElementById('emergency-repair');
const cloudStatus=document.getElementById('cloud-action-status');
const repairCenter=document.getElementById('cloud-repair-center');
let cloudActionRunning=false;
function setCloudStatus(message,state=''){cloudStatus.textContent=message;cloudStatus.className='cloud-action-status'+(state?' '+state:'');}
function setCloudBusy(busy){cloudActionRunning=busy;updateButton.disabled=busy;repairButton.disabled=busy;}
function freshUrl(path){return path+(path.includes('?')?'&':'?')+'t='+Date.now();}
function pause(ms){return new Promise(resolve=>setTimeout(resolve,ms));}
function taipeiNow(){const parts=new Intl.DateTimeFormat('zh-TW',{timeZone:'Asia/Taipei',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',hourCycle:'h23'}).formatToParts(new Date());const p=Object.fromEntries(parts.map(x=>[x.type,x.value]));return p.year+'-'+p.month+'-'+p.day+' '+p.hour+':'+p.minute+':'+p.second;}
function showStoredTimes(){const manual=localStorage.getItem('tw649-manual-update-time')||'尚未手動更新';const repair=localStorage.getItem('tw649-repair-time')||'尚未執行';document.querySelectorAll('[data-manual-time]').forEach(x=>x.textContent=manual);document.querySelectorAll('[data-repair-time]').forEach(x=>x.textContent=repair);}
async function fetchJson(path,timeout=10000){const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),timeout);try{const response=await fetch(freshUrl(path),{cache:'no-store',headers:{'Cache-Control':'no-cache'},signal:controller.signal});if(!response.ok)throw new Error(path+' HTTP '+response.status);return await response.json();}finally{clearTimeout(timer);}}
function forceFreshReload(reason){const url=new URL(location.href);url.searchParams.set('cloud_refresh',Date.now());url.searchParams.set('reason',reason);location.replace(url.toString());}
function validateCloudBundle(version,analysis,selfTest,repairStatus){if(!version.hash||!version.latest_period)throw new Error('版本資料不完整');if(String(analysis?.latest_draw?.period)!==String(version.latest_period))throw new Error('期別不同步');if(selfTest.passed!==true)throw new Error('全系統自測未通過');if(!['healthy','awaiting_verification'].includes(repairStatus.status))throw new Error('雲端修復狀態異常');return version;}
async function manualUpdateLatest(){if(cloudActionRunning)return;setCloudBusy(true);repairCenter.classList.remove('show');setCloudStatus('正在跳過快取取得最新戰報…','working');try{const [version,analysis,selfTest]=await Promise.all([fetchJson('version.json'),fetchJson('latest_analysis.json'),fetchJson('self_test_report.json')]);if(!version.hash||String(analysis?.latest_draw?.period)!==String(version.latest_period))throw new Error('雲端期別核對失敗');if(selfTest.passed!==true)throw new Error('雲端全系統檢測未通過');localStorage.setItem('tw649-version',version.hash);const completed=taipeiNow();localStorage.setItem('tw649-manual-update-time',completed);showStoredTimes();if(version.hash!==pageHash){setCloudStatus('發現新版：第 '+version.latest_period+' 期；完成時間 '+completed+'，正在載入。','success');await pause(700);forceFreshReload('manual');return;}setCloudStatus('檢查完成：'+completed+'／第 '+version.latest_period+' 期，目前已是最新，不需重新載入。','success');setCloudBusy(false);}catch(error){setCloudStatus('手動更新失敗：'+error.message+'。請按「當機立即修復」。','failure');setCloudBusy(false);}}
async function clearBrokenClientState(){if('serviceWorker'in navigator){const registrations=await navigator.serviceWorker.getRegistrations();await Promise.all(registrations.map(registration=>registration.unregister()));}if('caches'in window){const keys=await caches.keys();await Promise.all(keys.map(key=>caches.delete(key)));}localStorage.removeItem('tw649-version');}
async function immediateRepair(){if(cloudActionRunning)return;setCloudBusy(true);repairCenter.classList.remove('show');setCloudStatus('正在清除失效快取與背景程式…','working');let lastError=new Error('未知錯誤');try{await clearBrokenClientState();}catch(error){lastError=error;}for(let attempt=1;attempt<=3;attempt++){setCloudStatus('立即修復第 '+attempt+'/3 輪：核對雲端資料…','working');try{const [version,analysis,selfTest,repairStatus]=await Promise.all([fetchJson('version.json'),fetchJson('latest_analysis.json'),fetchJson('self_test_report.json'),fetchJson('self_repair_status.json')]);validateCloudBundle(version,analysis,selfTest,repairStatus);localStorage.setItem('tw649-version',version.hash);const completed=taipeiNow();localStorage.setItem('tw649-repair-time',completed);showStoredTimes();setCloudStatus('修復成功：'+completed+'／第 '+version.latest_period+' 期資料完整，正在重新載入。','success');await pause(1000);forceFreshReload('repair');return;}catch(error){lastError=error;if(attempt<3)await pause(attempt*1200);}}setCloudStatus('三輪修復未通過：'+lastError.message+'。雲端看門狗仍會持續自動修復。','failure');repairCenter.classList.add('show');setCloudBusy(false);}
updateButton.addEventListener('click',manualUpdateLatest);repairButton.addEventListener('click',immediateRepair);
async function refreshVersion(){try{const version=await fetchJson('version.json');const old=localStorage.getItem('tw649-version');if(old&&old!==version.hash){localStorage.setItem('tw649-version',version.hash);forceFreshReload('automatic');}else localStorage.setItem('tw649-version',version.hash);}catch(error){setCloudStatus('雲端版本檢查暫時失敗，可使用立即修復。','failure');}}
showStoredTimes();refreshVersion();setInterval(refreshVersion,60000);document.addEventListener('visibilitychange',()=>{if(!document.hidden)refreshVersion()});window.addEventListener('pageshow',()=>{showStoredTimes();refreshVersion()});if('serviceWorker'in navigator)navigator.serviceWorker.register('service-worker.js').then(registration=>registration.update()).catch(()=>{});